name: deploy

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./ui

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - run: npm ci
      - run: npm run lint
      - run: git config --global user.email "akam476@hawaii.edu"
      - run: git config --global user.name "Aaron-Kam"
      - run: git remote set-url origin https://ACCESS-Advising:${{ secrets.GITHUB_TOKEN }}@github.com/ACCESS-Advising/access-dashboard.git
      - run: npm run deploy

